### ISSUE TITLE
init template error

### ISSUE THREAD

**Issue by limichange** [vitejs/create-vite-app#32]
## npm init
```shell
❱❱❱ npm init vite-app wuhan-admin4 --template react-ts  
```

## yarn dev
```shell
❱❱❱ yarn dev
yarn run v1.22.4
warning package.json: No license field
$ vite
vite v1.0.0-beta.1
[vite] failed to load config from /Users/limichange/limiCode/wuhan-admin4/vite.config.ts:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/limichange/limiCode/wuhan-admin4/node_modules/rollup/dist/es/rollup.browser.js
require() of ES modules is not supported.
require() of /Users/limichange/limiCode/wuhan-admin4/node_modules/rollup/dist/es/rollup.browser.js from /Users/limichange/limiCode/wuhan-admin4/node_modules/vite/dist/config.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename rollup.browser.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/limichange/limiCode/wuhan-admin4/node_modules/rollup/dist/es/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:13)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.resolveConfig (/Users/limichange/limiCode/wuhan-admin4/node_modules/vite/dist/config.js:57:28)
    at resolveOptions (/Users/limichange/limiCode/wuhan-admin4/node_modules/vite/dist/cli.js:117:39)
    at /Users/limichange/limiCode/wuhan-admin4/node_modules/vite/dist/cli.js:65:27
    at Object.<anonymous> (/Users/limichange/limiCode/wuhan-admin4/node_modules/vite/dist/cli.js:79:3)
    at Module._compile (internal/modules/cjs/loader.js:1144:30) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by underfin** [comment]
I can't reproduction it.Is it I missed something?

**Comment by yyx990803** [comment]
Can't reproduce either.

**Comment by limichange** [comment]
I just find the reason. Because of my node version. If nodejs version is 13, it will report the error. now, I upgrade my nodejs version to 14, anything is ok. Thanks of everybody.
![image](https://user-images.githubusercontent.com/1947344/85805945-4afccd80-b780-11ea-83d0-8648067854af.png)
